### ISSUE TITLE
Make mockery immune to its own cache clearing

### ISSUE THREAD

**Issue by cspotcode** [cspotcode/mockery-next#7]
Consider the following test:

```
var mockery = require('mockery');
mockery.enable({useCleanCache: true});
require('./otherTests');
```

And in other-tests.js:

```
var mockery = require('mockery');
mockery.registerMock('util', utilMock);
```

Since mockery is enabled with a clean cache, other-tests will require() a totally new instance of mockery.  `registerMock` won't do anything because it's not applying to the enabled instance.

The fix is to make sure mockery is always cached even when it has enabled a clean cache.  Mockery can either attach itself to the "module" module or simply place itself into the clean cache.

**Comment by davidporter-id-au** [comment]
Cool, thanks for the heads up, I'll check it out when I'm in the office next
